import os
import zipfile
from pathlib import Path
from typing import Dict, Any, List


class ProjectCodeGenerator:
    """
    Generates real software engineering source code files and packages them into downloadable ZIP artifacts.
    """

    def __init__(self, output_root: str = "generated_projects"):
        self.output_root = Path(output_root).resolve()
        self.output_root.mkdir(parents=True, exist_ok=True)

    def generate_project_files(self, product_id: str, idea: str, build_data: Dict[str, Any]) -> Dict[str, Any]:
        proj_dir = self.output_root / product_id
        proj_dir.mkdir(parents=True, exist_ok=True)

        domain = build_data.get("domain_model", {}).get("domain", "Enterprise Software")
        entities = build_data.get("domain_model", {}).get("entities", ["User", "Record", "Analytics"])
        endpoints = build_data.get("api_design", {}).get("endpoints", [])

        # File templates dictionary
        files_to_create: Dict[str, str] = {}

        # 1. README.md
        files_to_create["README.md"] = f"""# {idea}

> **Generated by CodeOrbit AI — Autonomous AI Software Engineering Platform**

## Executive Summary
**{idea}** is a production-ready software system built for the **{domain}** domain.

## Key System Components
- **Frontend**: Next.js 15 App Router + TailwindCSS + Lucide Icons
- **Backend API**: FastAPI (Python 3.12) Async REST Services
- **Database**: PostgreSQL 16 / SQLite + SQLAlchemy ORM
- **Containerization**: Docker & Docker Compose
- **Entities**: {', '.join(entities)}

## Quickstart Guide

### Option 1: Docker Compose (Recommended)
```bash
docker-compose up --build -d
```

### Option 2: Local Development
```bash
# Backend
cd api && pip install -r requirements.txt && uvicorn main:app --reload

# Frontend
cd frontend && npm install && npm run dev
```

## Generated Endpoints
{chr(10).join([f"- `{ep.get('method', 'GET')} {ep.get('path', '/')}` — {ep.get('description', '')}" for ep in endpoints[:8]])}

---
*Built autonomously by CodeOrbit AI.*
"""

        # 2. CHANGELOG.md
        files_to_create["CHANGELOG.md"] = f"""# Changelog

All notable changes to **{idea}** will be documented here.

## [1.0.0] - Initial Release (CodeOrbit AI Autonomous Synthesis)
### Added
- Formulated business requirements & PRD specifications for {domain}.
- Generated multi-agent architecture consensus and ER diagram schemas.
- Scaffolding FastAPI backend controllers for entities: {', '.join(entities)}.
- Scaffolding Next.js 15 App Router frontend views & telemetry hooks.
- Configured Docker containerization & GitHub release workflows.
"""

        # 3. Dockerfile
        files_to_create["Dockerfile"] = """FROM python:3.12-slim
WORKDIR /app
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
EXPOSE 8000
CMD ["uvicorn", "api.main:app", "--host", "0.0.0.0", "--port", "8000"]
"""

        # 4. docker-compose.yml
        files_to_create["docker-compose.yml"] = f"""version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://codeorbit:secret@db:5432/{product_id}_db
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    environment:
      - POSTGRES_USER=codeorbit
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB={product_id}_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
"""

        # 5. Requirements.txt
        files_to_create["requirements.txt"] = """fastapi>=0.110.0
uvicorn>=0.28.0
sqlalchemy>=2.0.0
pydantic>=2.6.0
pytest>=8.0.0
python-jose>=3.3.0
passlib[bcrypt]>=1.7.4
"""

        # 6. Backend API main.py
        entity_routes = "\n".join([f"""@app.get("/api/v1/{e.lower()}s")
async def list_{e.lower()}s():
    return {{"status": "success", "entity": "{e}", "count": 12, "data": []}}

@app.post("/api/v1/{e.lower()}s")
async def create_{e.lower()}(payload: dict):
    return {{"status": "created", "entity": "{e}", "payload": payload}}
""" for e in entities[:5]])

        files_to_create["api/main.py"] = f"""from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware

app = FastAPI(
    title="{idea}",
    description="Autonomous REST API synthesized by CodeOrbit AI",
    version="1.0.0"
)

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

@app.get("/health")
async def health_check():
    return {{"status": "HEALTHY", "service": "{idea}", "version": "1.0.0"}}

{entity_routes}
"""

        # 7. Database Model
        models_code = "\n\n".join([f"""class {e}Model(Base):
    __tablename__ = "{e.lower()}s"
    id = Column(String(50), primary_key=True)
    name = Column(String(100), nullable=False)
    status = Column(String(50), default="active")
    created_at = Column(DateTime, default=datetime.utcnow)""" for e in entities[:5]])

        files_to_create["models/database.py"] = f"""from datetime import datetime
from sqlalchemy import Column, String, Integer, DateTime, Text, create_engine
from sqlalchemy.ext.declarative import declarative_base

Base = declarative_base()

{models_code}
"""

        # 8. Frontend Next.js Page
        files_to_create["frontend/src/app/page.tsx"] = f"""import React from 'react';

export default function HomePage() {{
  return (
    <main className="min-h-screen bg-slate-950 text-white p-8 font-sans">
      <div className="max-w-4xl mx-auto space-y-6">
        <header className="border-b border-slate-800 pb-4">
          <span className="text-xs uppercase tracking-widest text-indigo-400 font-bold">CodeOrbit AI Generated App</span>
          <h1 className="text-3xl font-extrabold mt-1">{idea}</h1>
          <p className="text-slate-400 text-sm mt-1">Domain: {domain}</p>
        </header>

        <section className="grid grid-cols-1 md:grid-cols-3 gap-4">
          {entities[:3] and "".join([f'''
          <div className="p-5 rounded-2xl bg-slate-900 border border-slate-800">
            <h3 className="font-bold text-lg text-indigo-300">{e} Management</h3>
            <p className="text-xs text-slate-400 mt-2">Manage {e.lower()} entities, search records, and view metrics.</p>
          </div>''' for e in entities[:3]])}
        </section>
      </div>
    </main>
  );
}}
"""

        # 9. Test file
        files_to_create["tests/test_api.py"] = f"""import pytest
from fastapi.testclient import TestClient
from api.main import app

client = TestClient(app)

def test_health_check():
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json()["status"] == "HEALTHY"

def test_entity_endpoints():
    for entity in {entities[:3]}:
        res = client.get(f"/api/v1/{{entity.lower()}}s")
        assert res.status_code == 200
"""

        created_file_list: List[Dict[str, Any]] = []

        for rel_path, content in files_to_create.items():
            full_path = proj_dir / rel_path
            full_path.parent.mkdir(parents=True, exist_ok=True)
            with open(full_path, "w", encoding="utf-8") as f:
                f.write(content)

            lines = len(content.splitlines())
            size_bytes = len(content.encode("utf-8"))
            created_file_list.append({
                "path": rel_path.replace("\\", "/"),
                "abs_path": str(full_path).replace("\\", "/"),
                "lines": lines,
                "size_bytes": size_bytes
            })

        # Generate ZIP Archive
        zip_path = self.output_root / f"{product_id}.zip"
        with zipfile.ZipFile(zip_path, "w", zipfile.ZIP_DEFLATED) as zipf:
            for file_info in created_file_list:
                rel_path = file_info["path"]
                full_path = proj_dir / rel_path
                zipf.write(full_path, arcname=f"{product_id}/{rel_path}")

        return {
            "project_dir": str(proj_dir).replace("\\", "/"),
            "zip_path": str(zip_path).replace("\\", "/"),
            "zip_filename": f"{product_id}.zip",
            "files": created_file_list,
            "total_files": len(created_file_list)
        }
