import json
import math
import os
import threading
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Dict, List, Optional, Tuple
from pydantic import BaseModel, Field

from config import settings
from core.logging import get_logger

logger = get_logger("Memory")

class LogEntry(BaseModel):
    """Represents a log generated by an agent or system step execution."""
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).replace(tzinfo=None).isoformat())
    agent: str
    message: str
    level: str = "INFO"

class MessageEntry(BaseModel):
    """Represents a message sent between two agents (communication history)."""
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).replace(tzinfo=None).isoformat())
    sender: str
    receiver: str
    content: str

class MemoryState(BaseModel):
    """Defines the complete state structure of shared memory sessions."""
    data: Dict[str, Any] = Field(default_factory=dict)
    logs: List[LogEntry] = Field(default_factory=list)
    messages: List[MessageEntry] = Field(default_factory=list)
    status: str = "idle"
    task_id: Optional[str] = None
    created_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).replace(tzinfo=None).isoformat())
    updated_at: str = Field(default_factory=lambda: datetime.now(timezone.utc).replace(tzinfo=None).isoformat())

class SharedMemory:
    """
    Shared memory manager facilitating agent state sharing, agent-to-agent messaging,
    task history tracking, and transactional SQLite persistence.
    """
    def __init__(self, session_id: Optional[str] = None):
        self.session_id = session_id or "default_session"
        self.state = MemoryState(task_id=self.session_id)
        self.load()

    def set(self, key: str, value: Any) -> None:
        """Store a key-value pair in shared memory and log the modification."""
        import re
        # Validate key
        if not isinstance(key, str) or not re.match(r"^[a-zA-Z0-9_\-]+$", key) or len(key) > 100:
            raise ValueError(f"Invalid memory key '{key}'. Keys must be alphanumeric with dashes/underscores and under 100 characters.")
            
        # Reserved keys check
        if key in ("task_id", "created_at", "updated_at"):
            raise ValueError(f"Memory key '{key}' is reserved and cannot be modified.")

        # Validate and sanitize value (ensure JSON serializable and enforce sizes)
        try:
            # Enforce size limits on value to prevent memory exhaustion
            serialized = json.dumps(value)
            if len(serialized) > 5 * 1024 * 1024:  # 5MB limit
                raise ValueError("Value size exceeds the maximum permitted memory value limit of 5MB.")
            # Reload to keep parsed structure but ensure it is strictly json-serializable
            sanitized_value = json.loads(serialized)
        except (TypeError, OverflowError) as te:
            raise ValueError(f"Invalid memory value for key '{key}': Must be JSON serializable. Error: {te}")
            
        self.state.data[key] = sanitized_value
        self.state.updated_at = datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
        
        # Keep backward compatibility logs updated
        self.add_log("system", f"Memory key '{key}' updated.")
        self.save()

    def get(self, key: str, default: Any = None) -> Any:
        """Retrieve a key from shared memory."""
        return self.state.data.get(key, default)

    def add_log(self, agent: str, message: str, level: str = "INFO") -> None:
        """Record an execution log entry for an agent or workflow step."""
        entry = LogEntry(agent=agent, message=message, level=level)
        self.state.logs.append(entry)
        self.state.updated_at = datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
        logger.info(f"[{agent}] {message}")
        
        try:
            from core.database import get_db_session
            from core.repositories import TaskRepository
            with get_db_session() as session:
                task_repo = TaskRepository(session)
                task_repo.add_log(self.session_id, source=agent, message=message, level=level)
        except Exception as e:
            logger.error(f"Failed to add log entry in SQLite: {str(e)}")
            
        self.save()

    def add_message(self, sender: str, receiver: str, content: str) -> None:
        """Log an agent-to-agent message."""
        entry = MessageEntry(sender=sender, receiver=receiver, content=content)
        self.state.messages.append(entry)
        self.state.updated_at = datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
        
        try:
            from core.database import get_db_session
            from core.repositories import TaskRepository
            with get_db_session() as session:
                task_repo = TaskRepository(session)
                task_repo.add_message(self.session_id, role=receiver, agent_name=sender, content=content)
        except Exception as e:
            logger.error(f"Failed to add agent message in SQLite: {str(e)}")
            
        # Log communication in main logs
        self.add_log("system", f"Agent Communication: {sender} -> {receiver}: {content}")

    def update_status(self, status: str) -> None:
        """Update the overall status of the current workflow session."""
        self.state.status = status
        self.state.updated_at = datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
        self.add_log("system", f"Workflow session status changed to '{status}'")
        self.save()

    def get_logs(self) -> List[str]:
        """Backward compatibility: return list of string logs."""
        return [f"{log.timestamp} [{log.level}] [{log.agent}] {log.message}" for log in self.state.logs]

    def show(self) -> Dict[str, Any]:
        """Return the dictionary data stored in memory (backward compatible)."""
        return self.state.data

    def save(self) -> None:
        """Persist memory state to SQLite database transactionally."""
        try:
            from core.database import get_db_session
            from core.repositories import TaskRepository, WorkflowRepository
            
            with get_db_session() as session:
                task_repo = TaskRepository(session)
                db_task = task_repo.get_task(self.session_id)
                if not db_task:
                    db_task = task_repo.create_task(
                        task_id=self.session_id,
                        payload={},
                        task_type="workflow"
                    )
                
                # Exclude workflow_steps from variables_json to keep it clean, as they are stored in workflow_executions
                data_copy = dict(self.state.data)
                data_copy.pop("workflow_steps", None)
                
                db_task.variables_json = data_copy
                db_task.status = self.state.status
                task_repo.save_task(db_task)
                
                # Persist workflow steps if present
                steps = self.state.data.get("workflow_steps")
                if steps:
                    work_repo = WorkflowRepository(session)
                    existing_steps = {s.step_id: s for s in work_repo.get_steps(self.session_id)}
                    
                    for step_dict in steps:
                        step_id = step_dict.get("step_id")
                        name = step_dict.get("name", "Unnamed Step")
                        desc = step_dict.get("description", "")
                        agent = step_dict.get("assigned_agent", "developer")
                        status = step_dict.get("status", "pending")
                        result = step_dict.get("result")
                        started_at = datetime.fromisoformat(step_dict.get("started_at")) if step_dict.get("started_at") else None
                        completed_at = datetime.fromisoformat(step_dict.get("completed_at")) if step_dict.get("completed_at") else None
                        
                        if step_id in existing_steps:
                            work_repo.update_step(
                                task_id=self.session_id,
                                step_id=step_id,
                                status=status,
                                result=result,
                                started_at=started_at,
                                completed_at=completed_at
                            )
                        else:
                            work_repo.create_step(
                                task_id=self.session_id,
                                step_id=step_id,
                                name=name,
                                description=desc,
                                assigned_agent=agent,
                                status=status
                            )
                            if result or started_at or completed_at:
                                work_repo.update_step(
                                    task_id=self.session_id,
                                    step_id=step_id,
                                    status=status,
                                    result=result,
                                    started_at=started_at,
                                    completed_at=completed_at
                                )
        except Exception as e:
            logger.error(f"Failed to persist memory session '{self.session_id}': {str(e)}")

    def load(self) -> None:
        """Load memory state from SQLite database."""
        try:
            from core.database import init_db, get_db_session
            from core.repositories import TaskRepository, WorkflowRepository
            
            init_db()
            
            with get_db_session() as session:
                task_repo = TaskRepository(session)
                db_task = task_repo.get_task(self.session_id)
                if not db_task:
                    db_task = task_repo.create_task(
                        task_id=self.session_id,
                        payload={},
                        task_type="workflow"
                    )
                
                self.state.status = db_task.status or "idle"
                self.state.task_id = self.session_id
                self.state.data = dict(db_task.variables_json or {})
                
                # Load logs
                db_logs = task_repo.get_logs(self.session_id)
                self.state.logs = [
                    LogEntry(
                        timestamp=log.timestamp.isoformat() if log.timestamp else datetime.now(timezone.utc).replace(tzinfo=None).isoformat(),
                        agent=log.source,
                        message=log.message,
                        level=log.level
                    )
                    for log in db_logs
                ]
                
                # Load messages
                db_messages = task_repo.get_messages(self.session_id)
                self.state.messages = [
                    MessageEntry(
                        timestamp=msg.timestamp.isoformat() if msg.timestamp else datetime.now(timezone.utc).replace(tzinfo=None).isoformat(),
                        sender=msg.agent_name,
                        receiver=msg.role,
                        content=msg.content
                    )
                    for msg in db_messages
                ]
                
                # Load workflow steps
                work_repo = WorkflowRepository(session)
                db_steps = work_repo.get_steps(self.session_id)
                if db_steps:
                    steps_list = []
                    for step in db_steps:
                        steps_list.append({
                            "step_id": step.step_id,
                            "name": step.name,
                            "description": step.description,
                            "assigned_agent": step.assigned_agent,
                            "status": step.status,
                            "result": step.result,
                            "started_at": step.started_at.isoformat() if step.started_at else None,
                            "completed_at": step.completed_at.isoformat() if step.completed_at else None
                        })
                    self.state.data["workflow_steps"] = steps_list
                
                logger.info(f"Loaded memory session '{self.session_id}' from SQLite database.")
        except Exception as e:
            logger.error(f"Failed to load memory session '{self.session_id}': {str(e)}")


# =====================================================================
# Semantic Vector Memory
# =====================================================================

class MemoryItem(BaseModel):
    """
    Structured vector memory representation.
    """
    text: str
    metadata: Dict[str, Any] = Field(default_factory=dict)
    vector: List[float]
    timestamp: str = Field(default_factory=lambda: datetime.now(timezone.utc).replace(tzinfo=None).isoformat())


class VectorMemoryIndex:
    """
    Thread-safe, lightweight vector index storing text embeddings in SQLite.
    Provides Cosine Similarity search over database records.
    """
    def __init__(self, index_name: str = "global_vector_index"):
        self.index_name = index_name
        self.items: List[MemoryItem] = []
        self._lock = threading.Lock()
        self.load()

    def load(self) -> None:
        with self._lock:
            try:
                from core.database import init_db, get_db_session
                from core.repositories import MemoryRepository
                
                init_db()
                with get_db_session() as session:
                    repo = MemoryRepository(session)
                    db_entries = repo.get_entries(self.index_name)
                    
                    self.items = []
                    for entry in db_entries:
                        meta = dict(entry.metadata_json or {})
                        vec = meta.pop("vector", [])
                        self.items.append(MemoryItem(
                            text=entry.text,
                            metadata=meta,
                            vector=vec,
                            timestamp=entry.timestamp.isoformat() if entry.timestamp else datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
                        ))
                    logger.info(f"Loaded {len(self.items)} vectors from SQLite for index: {self.index_name}")
            except Exception as e:
                logger.error(f"Failed to load vector index {self.index_name}: {str(e)}")

    def save(self) -> None:
        """Atomic write vector index file. (No-op in SQLite version, as add_memory saves on call)"""
        pass

    def add_memory(self, text: str, metadata: Optional[Dict[str, Any]] = None) -> None:
        from core.llm import get_embedding
        vector = get_embedding(text)
        item = MemoryItem(
            text=text,
            metadata=metadata or {},
            vector=vector
        )
        with self._lock:
            self.items.append(item)
        
        # Persist to SQLite
        try:
            from core.database import get_db_session
            from core.repositories import MemoryRepository
            with get_db_session() as session:
                repo = MemoryRepository(session)
                meta_json = dict(metadata or {})
                meta_json["vector"] = vector
                repo.add_entry(self.index_name, text, meta_json)
            logger.info(f"Added new semantic memory item to SQLite index '{self.index_name}'.")
        except Exception as e:
            logger.error(f"Failed to save semantic memory item: {str(e)}")

    def _cosine_similarity(self, vec_a: List[float], vec_b: List[float]) -> float:
        dot_product = sum(a * b for a, b in zip(vec_a, vec_b))
        norm_a = math.sqrt(sum(a * a for a in vec_a))
        norm_b = math.sqrt(sum(b * b for b in vec_b))
        if norm_a == 0 or norm_b == 0:
            return 0.0
        return dot_product / (norm_a * norm_b)

    def search(self, query: str, limit: int = 5) -> List[Tuple[MemoryItem, float]]:
        from core.llm import get_embedding
        query_vector = get_embedding(query)
        
        scores = []
        with self._lock:
            for item in self.items:
                similarity = self._cosine_similarity(query_vector, item.vector)
                scores.append((item, similarity))
                
        scores.sort(key=lambda x: x[1], reverse=True)
        return scores[:limit]

    def clear(self) -> None:
        with self._lock:
            self.items.clear()
        try:
            from core.database import get_db_session
            from core.repositories import MemoryRepository
            with get_db_session() as session:
                repo = MemoryRepository(session)
                repo.clear_entries(self.index_name)
            logger.info(f"Cleared vector index '{self.index_name}' in SQLite database.")
        except Exception as e:
            logger.error(f"Failed to clear vector index: {str(e)}")

# =====================================================================
# Memory Consolidation
# =====================================================================

class MemoryConsolidator:
    """
    Consolidator engine analyzing completed session traces (logs/messages)
    to summarize outcomes and persist abstract learnings to semantic long-term memory.
    """
    def __init__(self, vector_index: Optional[VectorMemoryIndex] = None):
        self.vector_index = vector_index or VectorMemoryIndex()

    def consolidate_session(self, session_id: str) -> Optional[str]:
        """
        Loads the session memory, extracts key summaries and learnings via Gemini,
        and saves the consolidated information to the vector memory index.
        """
        try:
            memory = SharedMemory(session_id=session_id)
            status = memory.state.status
            logs_str = "\n".join(memory.get_logs()[:200]) # Limit to prevent context overflow
            messages_str = "\n".join([f"{m.sender} -> {m.receiver}: {m.content}" for m in memory.state.messages[:100]])
            
            task_desc = memory.get("structured_plan", {}).get("project_title", "Unknown Task")
            if task_desc == "Unknown Task":
                plan_var = memory.get("plan")
                if plan_var:
                    task_desc = str(plan_var)[:100]
            
            prompt = f"""
            You are a Senior AI System Architect.
            Analyze the execution details of the completed session below and generate a consolidated knowledge entry.
            Extract key accomplishments, implementation decisions, styling specifications, mistakes made, 
            how errors were resolved, and abstract lessons learned.
            
            Session ID: {session_id}
            Status Outcome: {status}
            Task Objective/Context: {task_desc}
            
            --- EXECUTION LOGS ---
            {logs_str}
            
            --- AGENT CHAT MESSAGES ---
            {messages_str}
            
            ---
            Provide a clean structured summary in the following format:
            TASK SUMMARY:
            [Brief description of the task objective]
            
            KEY DECISIONS & IMPLEMENTATIONS:
            - [Decision A]
            - [Decision B]
            
            PROBLEMS & RESOLUTIONS:
            - [Error description] -> [How it was fixed]
            
            ABSTRACT LESSONS LEARNED:
            - [Lesson A]
            - [Lesson B]
            """
            
            from core.llm import ask_llm
            consolidated_text = ask_llm(
                prompt=prompt,
                system_instruction="You are a Knowledge Consolidation Agent. Synthesize raw session history into crisp architectural lessons."
            )
            
            metadata = {
                "session_id": session_id,
                "status": status,
                "type": "session_consolidation",
                "consolidated_at": datetime.now(timezone.utc).replace(tzinfo=None).isoformat()
            }
            self.vector_index.add_memory(consolidated_text, metadata)
            logger.info(f"Consolidated knowledge for session '{session_id}' successfully saved to long-term memory.")
            return consolidated_text
            
        except Exception as e:
            logger.error(f"Failed to consolidate session {session_id}: {str(e)}")
            return None